server:
  port: 9002

spring:
  application:
    name: saw-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LehongShan/SawConfigRepository
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
